version: '3'

services:
  nhctask:
    build: nihecaTask
    ports:
      - '8080:8080'
    environment:
      DB_URL: jdbc:mysql://nihecatask_bd:3306/bd_nihecatask?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      nihecatask_bd:
          condition: service_healthy
  nihecatask_bd:
    image: 'mysql:latest'
    ports:
      - '3307:3306'
    environment:
      - 'MYSQL_DATABASE=bd_nihecatask'
      - 'MYSQL_PASSWORD=1234'
      - 'MYSQL_ROOT_PASSWORD=1234'
    restart: always
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 10s
      retries: 10
