##FROM openjdk:17-jdk-slim
##ARG JAR_FILE=target/nihecaTask-1.0.jar
##COPY ${JAR_FILE} app_nihecatask.jar
##EXPOSE 8080
##ENTRYPOINT ["java","-jar","app_nihecatask.jar"]

# Etapa 1: Construcción
FROM maven:3.8.1-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Etapa 2: Ejecución
FROM openjdk:17-jdk-slim
WORKDIR /app
ARG JAR_FILE=target/nihecaTask-1.0.jar
COPY --from=build /app/${JAR_FILE} app_nihecatask.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app_nihecatask.jar"]